# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lbpy',
                'doc_host': 'https://Lightbridge-KS.github.io',
                'git_url': 'https://github.com/Lightbridge-KS/lbpy',
                'lib_path': 'lbpy'},
  'syms': { 'lbpy.core': {'lbpy.core.foo': ('core.html#foo', 'lbpy/core.py')},
            'lbpy.fs': { 'lbpy.fs.read_text_dir': ('fs.html#read_text_dir', 'lbpy/fs.py'),
                         'lbpy.fs.read_text_file': ('fs.html#read_text_file', 'lbpy/fs.py'),
                         'lbpy.fs.write_text_file': ('fs.html#write_text_file', 'lbpy/fs.py')},
            'lbpy.hello': {'lbpy.hello.say_hello': ('hello.html#say_hello', 'lbpy/hello.py')}}}
