# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lbpy',
                'doc_host': 'https://Lightbridge-KS.github.io',
                'git_url': 'https://github.com/Lightbridge-KS/lbpy',
                'lib_path': 'lbpy'},
  'syms': { 'lbpy.core': {'lbpy.core.foo': ('core.html#foo', 'lbpy/core.py')},
            'lbpy.docx': { 'lbpy.docx.read_docx': ('docx.html#read_docx', 'lbpy/docx.py'),
                           'lbpy.docx.read_docx_dir': ('docx.html#read_docx_dir', 'lbpy/docx.py'),
                           'lbpy.docx.read_docx_dir_df': ('docx.html#read_docx_dir_df', 'lbpy/docx.py')},
            'lbpy.fs': { 'lbpy.fs.list_dir': ('fs.html#list_dir', 'lbpy/fs.py'),
                         'lbpy.fs.read_text_dir': ('fs.html#read_text_dir', 'lbpy/fs.py'),
                         'lbpy.fs.read_text_file': ('fs.html#read_text_file', 'lbpy/fs.py'),
                         'lbpy.fs.write_text_file': ('fs.html#write_text_file', 'lbpy/fs.py')},
            'lbpy.hello': {'lbpy.hello.say_hello': ('hello.html#say_hello', 'lbpy/hello.py')},
            'lbpy.xml': {'lbpy.xml.extract_from_tags': ('xml.html#extract_from_tags', 'lbpy/xml.py')}}}
