# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_xml.ipynb.

# %% auto 0
__all__ = ['extract_from_tags']

# %% ../nbs/02_xml.ipynb 5
def extract_from_tags(string: str, tags: str):
     # Use regular expressions to find content between <summary> tags
    import re
    match = re.search(rf'<{tags}>\s*(.*?)\s*</{tags}>', string, re.DOTALL)
    if not match:
        print(f"No <{tags}> tags found in the input string.")
        return

    # Extract the JSON string
    return  match.group(1)
